[project]
name = "llm-study"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.1.0",
    "jupyter>=1.1.1",
    "sentencepiece>=0.2.1",
    "tokenizers>=0.22.1",
    "transformers>=4.57.1",
]
